/**
 * Bridges local instruction-advisor state to the AL 08 wire records and the forwarding queue.
 *
 * The split that makes this Pro: the cloud finds the pattern (some file is read in 62% of
 * sessions by four of six developers), the machine writes the text (which file, and the
 * sentence). Neither half can do the other's job. `suggestedText`, `evidence` and `title` never
 * leave this machine — only `suggestion_id` (hashed), the enums, and the numeric baseline.
 *
 * Lives in `src/team/`, not `src/forward/` — this is where `SessionSummaryCard` and
 * `SuggestionCard` are read.
 */

import * as fs from 'fs'
import * as path from 'path'
import { generateSuggestions, type SuggestionCard } from '../../instructionAdvisor'
import { detectInstructionFiles, readAllInstructionContent } from '../../instructionFiles'
import { computeBaseline } from '../../instructionEffectiveness'
import { deriveRepoKey } from '../forward/repoKey'
import {
  buildInstructionFileState,
  buildFileFootprints,
  buildSuggestionEvents,
  type FileFootprintInput,
  type SuggestionEventInput,
} from '../forward/buildInstructionTelemetry'
import type { InstructionFileKind, RollupPayload } from '../forward/schema'
import { SCHEMA_VERSION } from '../forward/schema'
import { repoKeyFingerprint } from '../forward/repoKey'
import { ForwardQueue } from '../forward/queue'
import { loadCredentials } from './credentials'
import type { SessionSummaryCard } from '../../summarizers/summarizerTypes'

const KIND_MAP: Record<string, InstructionFileKind> = {
  claude_code: 'claude_md',
  codex: 'agents_md',
  copilot: 'copilot_instructions',
}

/** ~4 chars/token — the same rough estimate the Advisor's arithmetic uses. */
function estimateTokens(bytes: number): number {
  return Math.round(bytes / 4)
}

/** What the ledger remembers about a suggestion whose full card the Advisor may no longer
 *  regenerate. Only the id, the enums — never the prose. */
export type LedgerCard = { id: string; category?: SuggestionCard['category']; priority?: SuggestionCard['priority']; targetAgents?: string[] }

export interface SuggestionLedger {
  /** Raw suggestion ids that have been applied, with their apply time. `card` lets an applied
   *  suggestion still emit an event after it stops being regenerated by the Advisor. */
  applied: Array<{ id: string; atIso: string; card?: LedgerCard }>
  dismissed: Array<{ id: string; atIso: string }>
  reverted: Array<{ id: string; atIso: string }>
}

export const EMPTY_LEDGER: SuggestionLedger = { applied: [], dismissed: [], reverted: [] }

/**
 * Builds the instruction-telemetry portion of a rollup for one repository. Returns `null` when
 * the repo can't be keyed. Pure — no queueing, no network.
 */
export async function buildInstructionRollup(
  workspace: string,
  sessions: SessionSummaryCard[],
  ledger: SuggestionLedger,
): Promise<RollupPayload | null> {
  const creds = loadCredentials()
  const rk = await deriveRepoKey(workspace, creds?.orgId ?? 'unlinked-preview')
  if (!rk.ok) return null
  const ctx = rk.ctx

  const wsSessions = sessions.filter(s => (s.workspace ?? '') === workspace || (s.workspace ?? '').startsWith(workspace))
  const existingText = safeReadInstructions(workspace)

  // instruction_files
  const files = detectInstructionFiles(workspace).map(f => {
    let lineCount = 0
    let lastModifiedIso: string | undefined
    if (f.exists) {
      lineCount = f.content.split('\n').length
      try { lastModifiedIso = fs.statSync(f.filePath).mtime.toISOString() } catch { /* ignore */ }
    }
    return buildInstructionFileState({
      present: f.exists,
      kind: KIND_MAP[f.agent] ?? 'other',
      path: f.relativePath,
      content: f.content,
      lineCount,
      lastModifiedIso,
    }, ctx)
  })

  // file_footprints — the hot-file frequency map getHotFileSuggestions already builds.
  const footprintInputs = buildFootprintInputs(wsSessions, workspace, existingText)
  const footprints = buildFileFootprints(footprintInputs, ctx)

  // suggestion_events
  const suggestionInputs = buildSuggestionEventInputs(wsSessions, existingText, ledger)
  const events = buildSuggestionEvents(suggestionInputs, ctx)

  const payload: RollupPayload = {
    schema_version: SCHEMA_VERSION,
    repo_key_fp: repoKeyFingerprint(ctx),
  }
  if (files.length > 0) payload.instruction_files = files
  if (footprints.length > 0) payload.file_footprints = footprints
  if (events.length > 0) payload.suggestion_events = events
  return payload
}

function safeReadInstructions(workspace: string): string {
  try { return readAllInstructionContent(workspace) } catch { return '' }
}

function buildFootprintInputs(sessions: SessionSummaryCard[], workspace: string, existingText: string): FileFootprintInput[] {
  if (sessions.length < 3) return []
  const total = sessions.length
  const readCount = new Map<string, number>()
  const earlyCount = new Map<string, number>()
  for (const s of sessions) {
    const files = [...new Set(s.filesRead ?? [])]
    files.forEach((f, i) => {
      readCount.set(f, (readCount.get(f) ?? 0) + 1)
      if (i < 3) earlyCount.set(f, (earlyCount.get(f) ?? 0) + 1)
    })
  }
  const lowerInstr = existingText.toLowerCase()
  const out: FileFootprintInput[] = []
  for (const [file, count] of readCount) {
    if (count / total < 0.4) continue
    const basename = file.replace(/\\/g, '/').split('/').pop() ?? file
    if (basename.length < 4) continue
    let tokenSize = 0
    try {
      const abs = path.isAbsolute(file) ? file : path.join(workspace, file)
      tokenSize = estimateTokens(fs.statSync(abs).size)
    } catch { /* file may be gone */ }
    out.push({
      path: file,
      sessionsRead: count,
      sessionsTotal: total,
      earlyReads: earlyCount.get(file) ?? 0,
      tokenSize,
      coveredByInstructions: lowerInstr.includes(basename.toLowerCase()),
    })
  }
  return out.sort((a, b) => b.sessionsRead - a.sessionsRead).slice(0, 300)
}

function buildSuggestionEventInputs(sessions: SessionSummaryCard[], existingText: string, ledger: SuggestionLedger): SuggestionEventInput[] {
  const suggestions = generateSuggestions(sessions, existingText)
  const byId = new Map(suggestions.map(s => [s.id, s]))
  const events: SuggestionEventInput[] = []

  // `surfaced` — one per suggestion the Advisor currently renders.
  for (const s of suggestions) {
    events.push(toEventInput(s, 'surfaced', new Date().toISOString(), sessions))
  }
  // applied / dismissed / reverted from the ledger.
  for (const a of ledger.applied) {
    const card = byId.get(a.id) ?? a.card
    if (card) events.push(toEventInput({ ...card, id: a.id }, 'applied', a.atIso, sessions, Date.parse(a.atIso)))
  }
  for (const d of ledger.dismissed) {
    const card: LedgerCard = byId.get(d.id) ?? { id: d.id }
    events.push(toEventInput(card, 'dismissed', d.atIso, sessions))
  }
  for (const r of ledger.reverted) {
    const card: LedgerCard = byId.get(r.id) ?? { id: r.id }
    events.push(toEventInput(card, 'reverted', r.atIso, sessions))
  }
  return events
}

function toEventInput(
  card: LedgerCard,
  action: SuggestionEventInput['action'],
  atIso: string,
  sessions: SessionSummaryCard[],
  baselineAtMs?: number,
): SuggestionEventInput {
  const b = baselineAtMs && !Number.isNaN(baselineAtMs) ? computeBaseline(sessions, baselineAtMs) : undefined
  return {
    id: card.id,
    category: card.category ?? 'context',
    priority: card.priority ?? 'medium',
    targetAgents: card.targetAgents ?? [],
    action,
    atIso,
    baseline: b ? { costAvg: b.costAvg, turnsAvg: b.turnsAvg, errorRate: b.errorRate, loopRate: b.loopRate, insufficient: b.insufficient } : undefined,
  }
}

/**
 * Builds the instruction rollup for `workspace` and appends it to the forwarding queue — a hard
 * no-op unless a team is linked.
 */
export async function maybeEnqueueInstructionTelemetry(
  workspace: string,
  sessions: SessionSummaryCard[],
  ledger: SuggestionLedger,
): Promise<boolean> {
  if (!loadCredentials()) return false
  const payload = await buildInstructionRollup(workspace, sessions, ledger)
  if (!payload || (!payload.instruction_files && !payload.file_footprints && !payload.suggestion_events)) return false
  return new ForwardQueue().enqueue(payload)
}
